### PR TITLE
Switch to whisper with mlx

### PR DESCRIPTION
**Pull request by doge-rgb**

### CODE REVIEW

**Comment by linyiLYi** [comment]
Nice. I'll take a look and perhaps update the README file.

**Comment by linyiLYi** [comment]
Has MLX already been supported by the whisper library?

**Comment by doge-rgb** [comment]
This is an official example from Apple: [https://github.com/ml-explore/mlx-examples/tree/main/whisper](https://github.com/ml-explore/mlx-examples/tree/main/whisper )
The folder has been forked from the official repository and includes some additional patches: [https://github.com/ml-explore/mlx-examples/pull/12](https://github.com/ml-explore/mlx-examples/pull/12)

**Comment by linyiLYi** [comment]
Thanks!

**Pull request merged**
